---
# tasks file for slave
- name: Installing docker and iproute-tc Package
  package:
    name: 
    - docker
    - iproute-tc
    state: present

- name: Starting docker services and enable it
  service:
    name: docker
    state: started
    enabled: yes
- name: change driver to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: driver

- name: Restarting docker service
  service:
    name: docker
    state: restarted
  when: driver.changed == true

- name: Configuring Yum repo for k8s
  yum_repository:
    description: repo for k8s
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl

- name: Installing kubeadm
  package:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enabling kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes



- name: Add rules to iproute-tc configuration file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
  register: rules

- name: Refreshing sysctl
  shell: "sysctl --system"
  when: rules.changed == true
